const LESSON_DEVICE_STATUS = {
  ACTIVE: "active",
  BLOCKED: "blocked",
};

const LESSON_DEVICE_STATUS_VALUES = Object.values(LESSON_DEVICE_STATUS);

const LESSON_DEVICE_ERROR = {
  REGISTERED_ELSEWHERE: "DEVICE_REGISTERED_ELSEWHERE",
  ACCESS_BLOCKED: "LESSON_ACCESS_BLOCKED",
};

const LESSON_DEVICE_EVENT_ACTION = {
  REGISTERED: "registered",
  ACCESS_DENIED_CONFLICT: "access_denied_conflict",
  ACCESS_DENIED_BLOCKED: "access_denied_blocked",
  RESET: "reset",
  BLOCKED: "blocked",
  UNBLOCKED: "unblocked",
  REVOKED_PASSWORD: "revoked_password",
};

const LESSON_DEVICE_EVENT_ACTION_VALUES = Object.values(
  LESSON_DEVICE_EVENT_ACTION,
);

module.exports = {
  LESSON_DEVICE_STATUS,
  LESSON_DEVICE_STATUS_VALUES,
  LESSON_DEVICE_ERROR,
  LESSON_DEVICE_EVENT_ACTION,
  LESSON_DEVICE_EVENT_ACTION_VALUES,
};
