const PROJECT_MAX_FILE_SIZE_BYTES = 50 * 1024 * 1024;
const PROJECT_MAX_GALLERY_FILES = 30;
const PROJECT_MAX_BLOCK_IMAGES = 50;
const PROJECT_MAX_THUMBNAIL_FILES = 1;
const PROJECT_MAX_TOTAL_FILES =
  PROJECT_MAX_THUMBNAIL_FILES +
  PROJECT_MAX_GALLERY_FILES +
  PROJECT_MAX_BLOCK_IMAGES;

module.exports = {
  PROJECT_MAX_FILE_SIZE_BYTES,
  PROJECT_MAX_GALLERY_FILES,
  PROJECT_MAX_BLOCK_IMAGES,
  PROJECT_MAX_THUMBNAIL_FILES,
  PROJECT_MAX_TOTAL_FILES,
};
